### PR TITLE
impr + bugs/soft deleting vectors, HQL test fixes, HQL ID prop access

### LINKED ISSUE #209: [Bug]: Hybrid Search Score Combination Logic Error - Vector Scores Overwrite BM25 Scores
### What happened?

# Bug Description
- The hybrid search implementation uses HashMap::insert() to add vector similarity scores, which overwrites any existing BM25 scores for the same document instead of combining them.

# Actual Behavior
- Documents that appear in both BM25 and vector search results lose their BM25 scores entirely
- Only the weighted vector similarity score is retained
- This defeats the purpose of hybrid search and can produce worse results than either method alone

# Expected Behavior
- Hybrid search should combine both BM25 and vector similarity scores for documents that appear in both result sets.

[bug.md](https://github.com/user-attachments/files/21197298/bug.md)

### Steps to reproduce

Perform a hybrid search where some documents appear in both BM25 and vector results
Compare individual BM25 scores vs. hybrid search scores
Observe that hybrid scores are lower than expected due to lost BM25 contributions

### Version

v1.0.109

### Environment

Development/Local

### Relevant log output

```shell

```

### Additional context

// Replace line 395:
combined_scores.insert(doc_id, (1.0 - alpha) * score as f32);

// With:
*combined_scores.entry(doc_id).or_insert(0.0) += (1.0 - alpha) * score as f32;

### PR DESCRIPTION
**Pull request by xav-db**
## Description

- Implemented soft deleting vectors. Done by `DROP <traversal resulting in vectors>`
- Made HQL tests fail properly when errors are present
- Fixed issues with ID property access e.g. `N<User>::ID` or `N<User>::{user_id: ID}` now work
- Spreading fields now works properly 

## Related Issues

Closes #209 

## Checklist when merging to main

- [x] No compiler warnings (if applicable)
- [x] Code is formatted with `rustfmt`
- [x] No useless or dead code (if applicable)
- [x] Code is easy to understand
- [x] Doc comments are used for all functions, enums, structs, and fields (where appropriate)
- [x] All tests pass
- [x] Performance has not regressed (assuming change was not to fix a bug)
- [x] Version number has been updated in `helix-cli/Cargo.toml` and `helixdb/Cargo.toml`
- [x] Lines are kept under 100 characters where possible
- [x] Code is good

### CODE REVIEW

File: helix-cli/src/args.rs [hunk 1]
```diff
@@ -117,14 +117,14 @@ pub struct StopCommand {
     #[clap(short, long, help = "Stop all running instances")]
     pub all: bool,
 
-    #[clap(help = "Instance ID to stop")]
+    #[clap(short, long, help = "Instance ID to stop")]
     pub cluster: Option<String>,
```
Comment (RaphaelDarley) [inline helix-cli/src/args.rs:121]: Its a bit confusing if the help refers to instance but the flag is --cluster or -c

File: helix-cli/src/main.rs [hunk 2]
```diff
@@ -21,7 +21,7 @@ mod types;
 mod utils;
 
 #[tokio::main]
-async fn main() {
+async fn main() -> Result<(), ()> {
```
Comment (RaphaelDarley) [inline helix-cli/src/main.rs:24]: This is fine for now, but Result<T, ()> is considered bad practice, you could use ExitCode instead

Comment (xav-db) [reply helix-cli/src/main.rs:24]: okay will change in future

File: helix-cli/src/args.rs (hunk 1 above)
Comment (xav-db) [reply helix-cli/src/args.rs:121]: agreed will change
